#!/bin/sh

if [ "$XDG_CURRENT_DESKTOP" != "mango" ] && [ "$DESKTOP_SESSION" != "mango" ]; then
  exit 0
fi

# Mango-specific hook
pkill waybar
waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css
